version: '3.8'

services:
  github-runner:
    image: myoung34/github-runner:latest
    container_name: organization-runner
    restart: always
    environment:
      # Required secrets - set these in Portainer Stack Environment variables
      ACCESS_TOKEN: ${ACCESS_TOKEN}
      ORG_NAME: ${ORG_NAME}
      RUNNER_SCOPE: org
      
      # Optimization and configuration
      LABELS: n100,self-hosted
      DISABLE_AUTO_UPDATE: "true"
      limit: 2 # Limit concurrent jobs per runner to avoid overloading
      RUNNER_WORKDIR: /_work
      
    volumes:
      # Docker-out-of-Docker (DooD) - Critical for "Zero-Waste"
      - /var/run/docker.sock:/var/run/docker.sock
      # Persist runner configuration and workspace
      - runner-data:/_work

    deploy:
      resources:
        limits:
          # Hard limit to protect the N100 host (16GB total)
          memory: 3072M 
          # Optional: Limit CPU to prevent starving other services
          cpus: '2.00'
        reservations:
          memory: 512M

volumes:
  runner-data:
