name: Service CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    # Uses the centralized workflow from the infrastructure repo
    # Replace 'my-org' with the actual organization name
    uses: ArkeonProject/organization-tools/.github/workflows/reusable-deploy.yml@main
    with:
      service_name: 'my-microservice'
      port: '3000'
      run_tests: true
    # secrets: inherit # Uncomment if secrets are needed
