name: Release

on:
  push:
    branches: [main]

jobs:
  publish:
    name: Publish Release
    uses: ArkeonProject/organization-tools/.github/workflows/release-publish.yml@v1
    with:
      create-github-release: true
    secrets: inherit
