name: CI - Universal (develop)

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  node-ci:
    name: Node.js CI
    runs-on: ubuntu-latest
    if: hashFiles('package.json') != ''
    steps:
      - uses: actions/checkout@v4
      - run: npm install -g pnpm@10 --force
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: pnpm run lint || echo "No lint script"
      - run: pnpm run test || echo "No test script"
      - run: pnpm run build

  python-ci:
    name: Python CI
    runs-on: ubuntu-latest
    if: hashFiles('pyproject.toml') != '' || hashFiles('requirements.txt') != ''
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - run: python -m pip install --upgrade pip
      - run: pip install -e '.[dev]' || pip install -r requirements.txt
      - run: pytest --cov=src --cov-report=term-missing || echo "No tests"

  docker-ci:
    name: Docker Build Test
    runs-on: ubuntu-latest
    if: hashFiles('Dockerfile') != ''
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: temp/test:ci
          cache-from: type=gha
          cache-to: type=gha,mode=max
